services:
  api-server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      # Hot reload source code and tests
      - "./src:/app/src"
      - "./tests:/app/tests"

      # Load tokenizer
      - "./tokenizer:/app/tokenizer"
