name: Semgrep Security Scan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Install semgrep
        run: pip install semgrep==1.168.0
      
      - name: Run semgrep
        run: |
          semgrep scan \
          --config semgrep-rules \
          --json \
          --output semgrep-results.json \
          src
      
      - name: Run Policy Script
        run: python scripts/semgrep_policy.py semgrep-results.json
