name: Semgrep Security Scan

on:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Install semgrep
        run: pip install semgrep
      
      - name: Run semgrep
        run: |
          semgrep scan \
          --config semgrep-rules \
          --error
